const constants = {
  INCREMENT_TREES: 'INCREMENT_TREES',
  DECREMENT_TREES: 'DECREMENT_TREES',
  FETCH_VALUE: 'FETCH_VALUE',
  FETCH_POSTS: 'FETCH_POSTS',
  FETCH_POST: 'FETCH_POST',
  CREATE_POST: 'CREATE_POST',
  CREATE_POST_ERROR: 'CREATE_POST_ERROR',
  LOGIN_ATTEMPT: 'LOGIN_ATTEMPT',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  VALIDATE_TITLE: 'VALIDATE_TITLE',
  VALIDATE_CONTENT: 'VALIDATE_CONTENT',
  VALIDATE_DESCRIPTION: 'VALIDATE_DESCRIPTION',
  VALIDATION_ERROR: 'VALIDATION_ERROR'
}

export default constants
